version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cfdiclient-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1c7yuzddlvvro"
s3_prefix = "cfdiclient-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
