version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dev-cfdiclient-sam"
s3_prefix = "dev-cfdiclient-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
disable_rollback = true
