AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  cfdiclient-sam

  Sample SAM Template for cfdiclient-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tracing: Active

Resources:
  CfdiClientStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/cfdiclient.asl.json
      DefinitionSubstitutions:
        SolicitaDescargaFunctionArn: !GetAtt SolicitaDescargaFunction.Arn
        VerificarDescargaFunctionArn: !GetAtt VerificarDescargaFunction.Arn
        DescargarPaqueteFunctionArn: !GetAtt DescargarPaqueteFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref SolicitaDescargaFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref VerificarDescargaFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref DescargarPaqueteFunction

  SolicitaDescargaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/solicita_descarga/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 10
      Architectures:
        - x86_64
      Policies:
        - S3FullAccessPolicy:
            BucketName: cfdi-masivo
      Environment:
        Variables:
          BUCKET_NAME: cfdi-masivo

  VerificarDescargaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/verificar_descarga/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 10
      Architectures:
        - x86_64
      Policies:
        - S3FullAccessPolicy:
            BucketName: cfdi-masivo
      Environment:
        Variables:
          BUCKET_NAME: cfdi-masivo

  DescargarPaqueteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/descargar_paquete/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 10
      Architectures:
        - x86_64
      Policies:
        - S3FullAccessPolicy:
            BucketName: cfdi-masivo
      Environment:
        Variables:
          BUCKET_NAME: cfdi-masivo
  
  SolicitaDescargaApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/solicita_descarga_api/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 10
      Architectures:
        - x86_64
      Policies:
        - S3FullAccessPolicy:
            BucketName: cfdi-masivo
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt CfdiClientStateMachine.Name
      Events:
        CfdiClient:
          Type: Api
          Properties:
            Path: /solicita-descarga
            Method: post
      Environment:
        Variables:
          BUCKET_NAME: cfdi-masivo
          STATE_MACHINE_ARN: !Ref CfdiClientStateMachine

Outputs:
  # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  CfdiClientStateMachineArn:
    Description: "State machine ARN"
    Value: !Ref CfdiClientStateMachine
  CfdiClientStateMachineRoleArn:
    Description: "IAM Role created for State machine based on the specified SAM Policy Templates"
    Value: !GetAtt CfdiClientStateMachineRole.Arn
